version: '3.4'

services:
  postgres:
    container_name: postgresdb
    image: postgis/postgis:13-3.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fangorn
      POSTGRES_PASSWORD: ent
      POSTGRES_DB: trees
    volumes:
      - "./provisioning:/provisioning"