version: "3"

services:
  postgres:
    env_file: ".env"
    # image: postgres:11.10
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fangorn
      POSTGRES_PASSWORD: ent
      POSTGRES_DB: trees
    volumes:
      - "./backup:/backup"
      - "./scripts:/scripts"
